### ISSUE TITLE
Context restore fails due to disposed bitmapdata

### ISSUE THREAD

**Issue by mrfrasier** [pol2095/Feathers-Extension-CircleProgress#2]
On lines 55 and 80 of CircleNative.as the bitmap datas used to create the circle and bow are disposed. This means when starling suffers a context loss and tries to restore, an error 2015 is dispatched (Invalid Bitmap Data).

I'm not too well-versed in collaborating on Github, and my quick solution could definitely be better, so I won't submit a PR, but here is what I did real quick to "fix" it.

in create():
```
var bitmapData:BitmapData = new BitmapData(radius*2, radius*2, true, 0x0);
			bitmapData.draw(backCircle);
			var bitmap:Bitmap = new Bitmap(bitmapData);
			var texture:Texture = Texture.fromBitmap(bitmap);
			// give the texture a way to recreate itself
			texture.root.onRestore = function():void{
				var restoreBMD:BitmapData = new BitmapData(radius*2, radius*2, true, 0x0);
				restoreBMD.draw(backCircle);
				texture.root.uploadBitmapData(restoreBMD);
			}
			var image:Image = new Image( texture );
			
			bitmapData.dispose();
			//circle.graphics.clear();
			//shape.graphics.clear();
			// backCircle.graphics.clear();
			// backShape.graphics.clear();
```

In getBow():

```
var bitmapData:BitmapData = new BitmapData(radius*2, radius*2, true, 0x0);
			bitmapData.draw(circle);
			var bitmap:Bitmap = new Bitmap(bitmapData);
			var texture:Texture = Texture.fromBitmap(bitmap);
			texture.root.onRestore = function():void{
				var restoreBow:Sprite = new Sprite();
				restoreBow.graphics.beginFill(0x0);
				drawPieMask(restoreBow.graphics, 100 - percentage, radius + radius / 20, radius, radius);
				restoreBow.graphics.endFill();
				circle.addChild(restoreBow);
				restoreBow.blendMode = BlendMode.ERASE;
				
				var restoreBMD:BitmapData = new BitmapData(radius*2, radius*2, true, 0x0);
				restoreBMD.draw(circle);
				texture.root.uploadBitmapData(restoreBMD);
				restoreBMD.dispose();
			}
			var image:Image = new Image( texture );
			
			bitmapData.dispose();
			circleBow.graphics.clear();
```

Again, you know your code better, so I'm sure there are improvements that can be made (do we need to clear graphics? I commented that out in one place, also maybe a full recreation is better than trying to keep some of the shapes around), but the general idea is to add an onRestore function to the textures recreate themselves in the case of context loss.

**Comment by mrfrasier** [comment]
Also note, this may affect the starling version of the circle as well since it uses RenderTextures, but I was only affected by (and fiddled with) CircleNative

**Comment by pol2095** [comment]
You're right, I think it's fixed, thanks.
